project_id = "bzufsrhmxaiqnmkvketb"

[functions.proxy-drive-image]
verify_jwt = false

[functions.admin-municipality-operations]
verify_jwt = false

[functions.process-real-data-excel]
verify_jwt = false

[functions.delete-recent-acts]
verify_jwt = false
