-- Restaurar datos oficiales de escaños por provincia
-- Distribución oficial del Congreso de los Diputados (350 escaños)

INSERT INTO public.provincial_seats (provincia, seats) VALUES
('Álava', 4),
('Albacete', 4),
('Alicante', 12),
('Almería', 6),
('Asturias', 8),
('Ávila', 3),
('Badajoz', 6),
('Barcelona', 32),
('Burgos', 4),
('Cáceres', 4),
('Cádiz', 9),
('Cantabria', 5),
('Castellón', 4),
('Ciudad Real', 5),
('Córdoba', 6),
('A Coruña', 8),
('Cuenca', 3),
('Girona', 6),
('Granada', 7),
('Guadalajara', 3),
('Guipúzcoa', 6),
('Huelva', 5),
('Huesca', 3),
('Jaén', 6),
('León', 5),
('Lleida', 4),
('Lugo', 4),
('Madrid', 37),
('Málaga', 11),
('Murcia', 10),
('Navarra', 5),
('Ourense', 4),
('Palencia', 3),
('Las Palmas', 8),
('Pontevedra', 7),
('La Rioja', 4),
('Salamanca', 4),
('Segovia', 3),
('Sevilla', 12),
('Soria', 3),
('Tarragona', 6),
('Santa Cruz de Tenerife', 7),
('Teruel', 3),
('Toledo', 6),
('Valencia', 16),
('Valladolid', 5),
('Vizcaya', 8),
('Zamora', 3),
('Zaragoza', 7),
('Ceuta', 1),
('Melilla', 1);