
-- Insertar datos de ejemplo de municipios españoles en la tabla mpca
INSERT INTO public.mpca (idm, municipio, idp, provincia, idca, ca) VALUES
(1, 'Barcelona', 8, 'Barcelona', 9, 'Cataluña'),
(2, 'Madrid', 28, 'Madrid', 13, 'Comunidad de Madrid'),
(3, 'Valencia', 46, 'Valencia', 10, 'Comunidad Valenciana'),
(4, 'Sevilla', 41, 'Sevilla', 1, 'Andalucía'),
(5, 'Zaragoza', 50, 'Zaragoza', 2, 'Aragón'),
(6, 'Málaga', 29, 'Málaga', 1, 'Andalucía'),
(7, 'Murcia', 30, 'Murcia', 14, 'Región de Murcia'),
(8, 'Palma', 7, 'Illes Balears', 4, 'Illes Balears'),
(9, 'Las Palmas de Gran Canaria', 35, 'Las Palmas', 5, 'Canarias'),
(10, 'Bilbao', 48, 'Bizkaia', 16, 'País Vasco'),
(11, 'Alicante', 3, 'Alicante', 10, 'Comunidad Valenciana'),
(12, 'Córdoba', 14, 'Córdoba', 1, 'Andalucía'),
(13, 'Valladolid', 47, 'Valladolid', 7, 'Castilla y León'),
(14, 'Vigo', 36, 'Pontevedra', 12, 'Galicia'),
(15, 'Gijón', 33, 'Asturias', 3, 'Principado de Asturias'),
(16, 'Hospitalet de Llobregat', 8, 'Barcelona', 9, 'Cataluña'),
(17, 'Vitoria-Gasteiz', 1, 'Álava', 16, 'País Vasco'),
(18, 'A Coruña', 15, 'A Coruña', 12, 'Galicia'),
(19, 'Granada', 18, 'Granada', 1, 'Andalucía'),
(20, 'Elche', 3, 'Alicante', 10, 'Comunidad Valenciana'),
(21, 'Oviedo', 33, 'Asturias', 3, 'Principado de Asturias'),
(22, 'Badalona', 8, 'Barcelona', 9, 'Cataluña'),
(23, 'Cartagena', 30, 'Murcia', 14, 'Región de Murcia'),
(24, 'Terrassa', 8, 'Barcelona', 9, 'Cataluña'),
(25, 'Jerez de la Frontera', 11, 'Cádiz', 1, 'Andalucía'),
(26, 'Sabadell', 8, 'Barcelona', 9, 'Cataluña'),
(27, 'Móstoles', 28, 'Madrid', 13, 'Comunidad de Madrid'),
(28, 'Santa Cruz de Tenerife', 38, 'Santa Cruz de Tenerife', 5, 'Canarias'),
(29, 'Alcalá de Henares', 28, 'Madrid', 13, 'Comunidad de Madrid'),
(30, 'Pamplona', 31, 'Navarra', 15, 'Comunidad Foral de Navarra'),
(31, 'Almería', 4, 'Almería', 1, 'Andalucía'),
(32, 'Fuenlabrada', 28, 'Madrid', 13, 'Comunidad de Madrid'),
(33, 'Donostia-San Sebastián', 20, 'Gipuzkoa', 16, 'País Vasco'),
(34, 'Leganés', 28, 'Madrid', 13, 'Comunidad de Madrid'),
(35, 'Burgos', 9, 'Burgos', 7, 'Castilla y León'),
(36, 'Santander', 39, 'Cantabria', 6, 'Cantabria'),
(37, 'Castellón de la Plana', 12, 'Castellón', 10, 'Comunidad Valenciana'),
(38, 'Getafe', 28, 'Madrid', 13, 'Comunidad de Madrid'),
(39, 'Albacete', 2, 'Albacete', 8, 'Castilla-La Mancha'),
(40, 'Alcorcón', 28, 'Madrid', 13, 'Comunidad de Madrid'),
(41, 'Logroño', 26, 'La Rioja', 17, 'La Rioja'),
(42, 'Badajoz', 6, 'Badajoz', 11, 'Extremadura'),
(43, 'Huelva', 21, 'Huelva', 1, 'Andalucía'),
(44, 'Salamanca', 37, 'Salamanca', 7, 'Castilla y León'),
(45, 'Tarragona', 43, 'Tarragona', 9, 'Cataluña'),
(46, 'Lleida', 25, 'Lleida', 9, 'Cataluña'),
(47, 'Marbella', 29, 'Málaga', 1, 'Andalucía'),
(48, 'León', 24, 'León', 7, 'Castilla y León'),
(49, 'Cádiz', 11, 'Cádiz', 1, 'Andalucía'),
(50, 'Dos Hermanas', 41, 'Sevilla', 1, 'Andalucía');
